version: '3'
services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
  spring2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    command: [ "nginx-debug", '-g', 'daemon off;' ]
    ports:
      - "80:80"